### ISSUE TITLE
Cosmetic: File upload spinner icon rotates the wrong direction

### ISSUE THREAD

**Issue by qdolan** [SleepHQ/bug-reports-and-feature-requests#1]
This is purely cosmetic but something I just noticed:

In the file upload section when adding files to the drop target, the spinner icon of two circular arrow heads rotates such that the arrows move backwards. The rotation also appears to be slightly off axis inducing a very slight wobble.

**Comment by adampal** [comment]
This is now fixed. Let me know if you're still seeing that wobble. I didn't notice it in testing.
