### ISSUE TITLE
Display changes for ASV machines

### ISSUE THREAD

**Issue by Respirator99** [SleepHQ/bug-reports-and-feature-requests#2]
A couple of changes are requested to better reflect the operation of ASV machines (and probably other bilevel types)

**Statistics**

- The pressure and EPAP fields are showing the same number - this is not correct. See attached comparison SleepHQ v Oscar
![ASV_Pressures](https://user-images.githubusercontent.com/102843075/161364610-bbe10e6f-7797-4fd3-b507-93c2e8021147.PNG)
![ASV_Pressures_Oscar](https://user-images.githubusercontent.com/102843075/161364743-b8c5df37-000c-4faa-a8c0-7ae85c6b65b6.PNG)

**Comment by adampal** [comment]
Hey @Respirator99 this should have been fixed a while ago. Just wanted to confirm with you before I close this issue.
